"""Hindi (Devanagari) and romanised Hinglish names of everyday goods, mapped to the English words BIS titles use.

The standards catalogue and the compulsory-certification listings are English-only, so a question such as
"दूध का IS क्या है" or "dudh ka IS kya hai" can only be matched once "दूध"/"dudh" becomes "milk". This lexicon is the
offline, instant part of that step (``manakmarg.reasoning.interpret`` adds a language-model rewrite, when configured,
for everything the lexicon does not cover).

Rules for entries:
* the target is the word BIS titles actually use ("milk", "dahi", "tooth paste"; check the catalogue), never an IS
  number;
* a romanised entry must not also be a common English or Hinglish function word (so no "ret", "tar", "man");
* ambiguous words map to their everyday sense ("लोहा" → "iron" the metal; the appliance is "इस्त्री" → "electric iron").

Spelling variants that differ only by chandrabindu/anusvara or nukta are matched automatically (see ``aliases``).
Add a word here, then add it to ``manakmarg/eval/queries.json`` so the evaluation keeps covering it.
"""

PRODUCT_LEXICON: dict[str, str] = {
    # dairy and food
    "दूध": "milk",
    "दुध": "milk",
    "dudh": "milk",
    "doodh": "milk",
    "दूध पाउडर": "milk powder",
    "मिल्क पाउडर": "milk powder",
    "घी": "ghee",
    "पनीर": "paneer",
    "दही": "dahi",
        "मक्खन": "butter",
    "makhan": "butter",
    "मख्खन": "butter",
    "छाछ": "buttermilk",
    "chhachh": "buttermilk",
    "मलाई": "cream",
    "खोया": "khoa",
    "खोवा": "khoa",
    "छेना": "chhana",
    "chhena": "chhana",
    "शहद": "honey",
    "shahad": "honey",
    "नमक": "salt",
    "namak": "salt",
    "चीनी": "sugar",
    "cheeni": "sugar",
    "गुड़": "jaggery",
    "chawal": "rice",
    "चावल": "rice",
    "गेहूं": "wheat",
    "गेहूँ": "wheat",
    "gehun": "wheat",
    "आटा": "wheat flour atta",
    "atta": "wheat flour atta",
    "मैदा": "maida",
    "बेसन": "besan",
    "दाल": "pulses",
    "तेल": "edible oil",
    "सरसों का तेल": "mustard oil",
    "सरसों तेल": "mustard oil",
    "नारियल तेल": "coconut oil",
    "चाय": "tea",
    "कॉफी": "coffee",
    "कॉफ़ी": "coffee",
    "मसाले": "spices",
    "मसाला": "spices",
    "हल्दी": "turmeric",
    "haldi": "turmeric",
    "मिर्च": "chillies",
    "लाल मिर्च": "chillies",
    "धनिया": "coriander",
    "जीरा": "cumin",
    "पानी": "water",
    "pani": "water",
    "पीने का पानी": "drinking water",
    "बोतलबंद पानी": "packaged drinking water",
    "मिनरल वाटर": "packaged natural mineral water",
    "बिस्कुट": "biscuits",
    "ब्रेड": "bread",
    "चॉकलेट": "chocolate",
    "जैम": "jam",
    "अचार": "pickles",
    "achar": "pickles",
    "आइसक्रीम": "ice cream",
    "शिशु आहार": "infant food",
    "बेबी फूड": "infant food",
    "अंडा": "eggs",
    "अंडे": "eggs",
    # household and kitchen
    "बाल्टी": "bucket",
    "balti": "bucket",
    "टंकी": "water storage tank",
    "पानी की टंकी": "water storage tank",
    "tanki": "water storage tank",
    "बोतल": "bottle",
    "डिब्बा": "container",
    "थाली": "plate",
    "गिलास": "tumbler",
    "चम्मच": "spoon",
    "चाकू": "knife",
    "कैंची": "scissors",
    "ताला": "padlock",
    "tala": "padlock",
    "दरवाजा": "door",
    "दरवाज़ा": "door",
    "खिड़की": "window",
    "कांच": "glass",
    "काँच": "glass",
    "kanch": "glass",
    "शीशा": "mirror",
    "साबुन": "soap",
    "sabun": "soap",
    "डिटर्जेंट": "detergent",
    "सर्फ": "detergent powder",
    "टूथपेस्ट": "tooth paste",
    "मंजन": "tooth paste",
    "शैम्पू": "shampoo",
    "अगरबत्ती": "agarbatti",
    "माचिस": "safety matches",
    "मोमबत्ती": "candles",
    "गद्दा": "mattress",
    "तकिया": "pillow",
    "कंबल": "blanket",
    "चादर": "bed sheet",
    "छाता": "umbrella",
    "खिलौना": "toys",
    "खिलौने": "toys",
    "डायपर": "diapers",
    "सैनिटरी पैड": "sanitary pads",
    "सेनेटरी पैड": "sanitary pads",
    # appliances and electrical
    "पंखा": "fan",
    "pankha": "fan",
    "छत का पंखा": "ceiling fan",
    "कूलर": "air cooler",
    "फ्रिज": "refrigerator",
    "फ़्रिज": "refrigerator",
    "fridge": "refrigerator",
    "एसी": "air conditioner",
    "चूल्हा": "stove",
    "गैस चूल्हा": "domestic gas stove",
    "सिलेंडर": "gas cylinder",
    "गैस सिलेंडर": "lpg cylinder",
    "इस्त्री": "electric iron",
    "मिक्सर": "mixer grinder",
    "मिक्सी": "mixer grinder",
    "हीटर": "heater",
    "गीजर": "water heater",
    "गीज़र": "water heater",
    "केतली": "kettle",
    "बल्ब": "led lamp",
    "ट्यूबलाइट": "tubular fluorescent lamp",
    "ट्यूब लाइट": "tubular fluorescent lamp",
    "स्विच": "switch",
    "प्लग": "plug",
    "सॉकेट": "socket outlet",
    "बैटरी": "battery",
    "मीटर": "meter",
    "बिजली मीटर": "electricity meter",
    "इन्वर्टर": "inverter",
    "पावर बैंक": "power bank",
    "चार्जर": "charger",
    "मोबाइल": "mobile phone",
    "मोबाइल फोन": "mobile phone",
    "टीवी": "television",
    "लैपटॉप": "laptop",
    "कैमरा": "camera",
    "सोलर पैनल": "solar panel",
    # construction and materials
    "सरिया": "steel bars",
    "ईंट": "bricks",
    "ईंटें": "bricks",
    "eent": "bricks",
    "रेत": "sand",
    "बालू": "sand",
    "गिट्टी": "coarse aggregate",
    "टाइल": "tiles",
    "टाइल्स": "tiles",
    "पेंट": "paint",
    "रंग रोगन": "paint",
    "पुट्टी": "putty",
    "प्लाईवुड": "plywood",
    "लकड़ी": "timber",
    "lakdi": "timber",
    "कागज": "paper",
    "कागज़": "paper",
    "kagaz": "paper",
    "लोहा": "iron",
    "loha": "iron",
    "पीतल": "brass",
    "peetal": "brass",
    "एल्यूमिनियम": "aluminium",
    "जस्ता": "zinc",
    "सीसा": "lead",
    "रबर": "rubber",
    "प्लास्टिक": "plastic",
    "कपड़ा": "textile fabric",
    "कपडा": "textile fabric",
    "kapda": "textile fabric",
    "सूती कपड़ा": "cotton fabric",
    "धागा": "yarn",
    "dhaga": "yarn",
    "रस्सी": "rope",
    "जूट": "jute",
    "बोरी": "sacks",
    "थैला": "bag",
    # footwear, vehicles, farm
    "जूता": "footwear",
    "जूते": "footwear",
    "joota": "footwear",
    "joote": "footwear",
    "चप्पल": "slippers",
    "chappal": "slippers",
    "साइकिल": "bicycle",
    "खाद": "fertilizer",
    "khaad": "fertilizer",
    "उर्वरक": "fertilizer",
    "बीज": "seeds",
    "कीटनाशक": "pesticide",
    "ट्रैक्टर": "tractor",
    "पंप": "pump",
    "मोटर": "motor",
}
